# Generated by Django 4.2.30 on 2026-04-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_user_last_used_totp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('CONNECTION_REQUEST', 'Connection Request'), ('CONNECTION_ACCEPTED', 'Connection Accepted'), ('NEW_POST', 'New Post from Connection'), ('COMPANY_ASSIGNED', 'Added as Company Recruiter'), ('JOB_APPLICATION', 'Job Application Received')], max_length=30),
        ),
    ]
