# version: '3.8'

services:
  # 1. Database (PostgreSQL)
  db:
    image: postgres:15-alpine
    restart: always # <-- ADDED
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=fcs_project
      - POSTGRES_USER=fcs_user
      - POSTGRES_PASSWORD=fcs_password
    # ports:
    #   - "5433:5432"
    expose:
      - "5432"

    deploy:
      resources:
        limits:
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m" # Keep max 10MB of logs
        max-file: "3"   # Keep only 3 files before deleting old ones

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fcs_user -d fcs_project"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. Caching (Redis)
  redis:
    image: redis:7-alpine
    restart: always # <-- ADDED
    ports:
      - "6379:6379"

  # 3. Backend (Django)
  backend:
    build: ./backend
    restart: always # <-- ADDED
    command: >
      sh -c "while ! nc -z db 5432; do sleep 1; done;
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
      - media_data:/app/media         # <-- I MOVED THEM HERE
      - static_data:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - DB_HOST=db
      - DB_NAME=fcs_project
      - DB_USER=fcs_user
      - DB_PASS=fcs_password
      - REDIS_HOST=redis
      - ALLOWED_HOSTS=*
      - SECRET_KEY=dev_secret_key_change_in_prod
      - DEBUG=False
      - EMAIL_HOST_USER=kdewansh16@gmail.com
      - EMAIL_HOST_PASSWORD=ocsapshsudhgbbxi
      - ADMIN_URL=portal-206-987-secure/

  # 4. Frontend (React + Vite)
  frontend:
    build: ./frontend
    restart: always # <-- ADDED
    # volumes:
    #   - ./frontend:/app
    #   - /app/node_modules
    # ports:
    #   - "5173:5173"
    # environment:
    #   - CHOKIDAR_USEPOLLING=true
    expose:
        - 5173
    

  nginx:
    image: nginx:alpine
    restart: always # <-- ADDED
    ports:
      - "443:443"
      - "80:80"
    deploy:
      resources:
        limits:
          memory: 256M 
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      -   media_data:/app/media
      -   static_data:/app/staticfiles
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - backend
      - frontend
    

volumes:
  postgres_data:
  media_data:
  static_data: