name: Deploy and Restart VM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  manage-server:
    # THIS IS THE MAGIC LINE: Tells GitHub to use YOUR machine, not theirs
    runs-on: self-hosted 
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Deploy Docker Containers
        # We just run the commands directly because we are already on the VM!
        run: |
          cd ~/FCS_Project
          docker-compose down
          docker-compose build --no-cache frontend
          docker-compose up -d